### ISSUE TITLE
Changing values in config file gives an error

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/projectLive_demo#7]
In the INCLUDE demo : 
Changing the facet from `year` to `assay` in the `Initiative activity` plot gives the following error:

```
Warning: Error in : At least one layer must contain all faceting variables: `assay`.
* Plot is missing `assay`
* Layer 1 is missing `assay`
  123: <Anonymous>
```
The plot seems to use `files` table which has the `assay` column values, so unsure what is causing this error.

**Comment by jaybee84** [comment]
changing `column` type to `character` resolved this issue

**Comment by jaybee84** [comment]
related issue:

Is there a way to select top 5 values in a column for faceting ?

**Comment by andrewelamb** [comment]
@jaybee84 Do you mean by count for that value or if you ordered them in a certain way the first 5 values?

Either way way we don't functionality for that ATM.

**Comment by jaybee84** [comment]
I was thinking counting for that value : e.g.
when I use `assay` as a facet instead of `year`, the plot becomes unreadable due to the high number of assays. For better readability we would need the control to facet the plot by the top 5 assays

**Comment by andrewelamb** [comment]
@jaybee84 Could you close this issue and start a new one for the top values for faceting?
